# SwiftLint Configuration for SurrealDB Swift Client

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - Tests/SurrealDBTests/Mocks
  - Package.swift

# Opt-in rules (carefully selected for gradual adoption)
opt_in_rules:
  - sorted_imports
  - empty_count
  - closure_spacing
  - redundant_nil_coalescing
  - array_init
  - attributes
  - closure_end_indentation
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_type_annotation
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments
  - force_unwrapping # Allow force unwrapping in tests

# Custom rule configurations
line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 600
  error: 1000

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 60
  error: 100

type_name:
  min_length: 2
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - db
    - to
    - at
    - i # Loop index

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2

# Severity overrides
force_cast: warning
force_try: warning

# Reporter type
reporter: "xcode"
